# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-14 18:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdetails',
            old_name='user_name',
            new_name='username',
        ),
    ]
