# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-15 10:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20160814_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='user_type',
            field=models.CharField(choices=[('customer', 'Customer'), ('kitchen', 'Office')], max_length=100),
        ),
    ]
