# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-19 19:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20160815_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='phnone',
            field=models.CharField(max_length=13, null=True),
        ),
    ]
