# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-19 19:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_userdetails_phnone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdetails',
            old_name='phnone',
            new_name='phone',
        ),
    ]
