# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-14 17:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menudetails',
            name='menu_category',
            field=models.CharField(choices=[('soup', 'Soup'), ('starter', 'Starter'), ('maincourse', 'Main Course'), ('dessert', 'Dessert')], max_length=20, null=True),
        ),
    ]
