# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-15 09:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_menudetails_menu_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menudetails',
            name='menu_description',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
