# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-13 09:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menu', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.FloatField()),
                ('create_date', models.DateTimeField(blank=True, default=datetime.datetime(2016, 8, 13, 9, 38, 30, 180519))),
                ('status', models.CharField(choices=[('preaparing', 'Preparing'), ('ready', 'Ready'), ('delivered', 'Delivered')], default='preaparing', max_length=20)),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='user.UserDetails')),
            ],
            options={
                'db_table': 'order_details',
            },
        ),
        migrations.CreateModel(
            name='OrderItemDetails',
            fields=[
                ('order_item_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.ImageField(max_length=20, upload_to='')),
                ('menuid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='menu.MenuDetails')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='user.UserDetails')),
            ],
            options={
                'db_table': 'order_item_details',
            },
        ),
    ]
