# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-16 06:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20160813_0952'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetails',
            name='amount',
        ),
        migrations.AddField(
            model_name='orderitemdetails',
            name='price',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
