# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-16 10:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20160816_0614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitemdetails',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
