# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-19 07:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_auto_20160816_1005'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderdetails',
            old_name='order_id',
            new_name='orderid',
        ),
        migrations.RemoveField(
            model_name='orderitemdetails',
            name='userid',
        ),
        migrations.AddField(
            model_name='orderitemdetails',
            name='orderid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='order.OrderDetails'),
            preserve_default=False,
        ),
    ]
