# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-19 17:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_auto_20160819_0705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetails',
            name='status',
            field=models.CharField(choices=[('preparing', 'Preparing'), ('ready', 'Ready'), ('delivered', 'Delivered')], default='preparing', max_length=20),
        ),
    ]
